// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using monedas.Models;

namespace monedas.Migrations
{
    [DbContext(typeof(MonedaContext))]
    partial class MonedaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("monedas.Monedas", b =>
                {
                    b.Property<string>("moneda")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ValorActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorMax")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("moneda");

                    b.ToTable("Monedas");
                });
#pragma warning restore 612, 618
        }
    }
}
